import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="px-8 py-2 flex justify-between gap-5 bg-stone-800 items-center">
          <img src="/burger.png" alt="" className="w-[80px]"/>

          <div className="space-x-5">
            <Link className="btn" href={"/foods"}>Foods</Link>
            <Link className="btn" href={"/reviews"}>Reviews</Link>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
